"""test database

Revision ID: 83305c19789c
Revises: 9bd83a9f020a
Create Date: 2023-09-09 15:42:00.287477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83305c19789c'
down_revision: Union[str, None] = '9bd83a9f020a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_events_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('event_ts', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_events_test')
    # ### end Alembic commands ###
