"""second revision

Revision ID: e94fc45fe91e
Revises: 6d3962443332
Create Date: 2023-09-09 08:44:34.660266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94fc45fe91e'
down_revision: Union[str, None] = '6d3962443332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('event_ts', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_events')
    # ### end Alembic commands ###
