"""first revision

Revision ID: f47c0202fcf8
Revises: 
Create Date: 2023-09-09 08:33:52.856244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47c0202fcf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_events',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('event_ts', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_events')
    # ### end Alembic commands ###
